### ISSUE TITLE
Dask error: Too many processors

### ISSUE THREAD

**Issue by topherconley** [aertslab/arboreto#2]
Hi Thomas, 

I have been trying out the [pySCENIC](https://github.com/aertslab/pySCENIC) tutorial script with my own test data, but have consistently found the same types of Dask-related errors when running `arboretum.grnboost2` on two different linux environments ( SLURM-managed single node and a big multi-core linux box).  Your colleague @bramvds, wrote the tutorial, but it fails at the `arboretum` function call. Following the tutorial as it was written exactly, which sets up a default `LocalCluster` internal to the function call, produced the same errors as explicitly controlling the number of workers as shown below: 

```
local_cluster = LocalCluster(n_workers=31, 
                             threads_per_worker=1)

custom_client = Client(local_cluster)
print(custom_client)

adjacencies = grnboost2(ex_matrix, 
                        tf_names=tf_names, 
                        verbose=True,
                        client_or_address=custom_client)
```

I attached the [Error Logs](https://github.com/tmoerman/arboretum/files/1996028/err.txt) in hopes you could diagnose what is going on? I think the diagnostic message is pretty clear, for someone familiar with the `Dask` framework, but I am not. 

> RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.
        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

```
            if __name__ == '__main__':
                freeze_support()
```

>   The "freeze_support()" line can be omitted if the program is not going to be frozen to produce an executable.

The same error shows up for this other python project on GitHub [here](https://github.com/pytorch/pytorch/issues/5858).

I should mention that I installed `pySCENIC` with `pip` as part of a recent `miniconda3` python 3.6.5 environment. 

Thanks in advance, 
Chris Conley

**Comment by tmoerman** [comment]
Hello Chris,

the error message is not specific to Dask but refers to a Python idiom that requires code that spawns  new Python processes (which Dask does under the hood of the grnboost2 and genie3 functions to parallelize the workload) to be wrapped in the "guardian" statement: `if __name__ == '__main__':`.

Try following modification to your script:

```
if __name__ == '__main__':
    local_cluster = LocalCluster(n_workers=31, 
                                 threads_per_worker=1)

    custom_client = Client(local_cluster)
    print(custom_client)

    adjacencies = grnboost2(ex_matrix, 
                            tf_names=tf_names, 
                            verbose=True,
                            client_or_address=custom_client)

```

More examples here: http://arboretum.readthedocs.io/en/latest/userguide.html

Kind regards,
Thomas

**Comment by topherconley** [comment]
Thanks Thomas, 
I am sorry I totally missed that big **Note** in your documentation (I am admittedly new to python, coming from R). The algorithm appears to be working as described now. I am going to post an issue to your colleague @bramvds, that he include the idiom in his tutorial, because you may get more traffic through him from other noobs like me. 
Best,
Chris
