### ISSUE TITLE
Why GENIE3/A outperforms GENIE3?

### ISSUE THREAD

**Issue by mr-september** [aertslab/arboreto#29]
In the paper, GENIE3/A was briefly mentioned to be a re-implementation of GENIE3, presumably for parallelizing (Dask).

However, in the comparison diagram, GENIE3/A consistently outperformed GENIE3 slightly.

![image](https://user-images.githubusercontent.com/45350177/114511260-05f84800-9c7b-11eb-947a-77018fbb0416.png)

Can the authors please clarify what else changed to cause this improvement in AUROC/AUPRC performance?

**Comment by tmoerman** [comment]
Genie3/A and Genie3 are equal from an algorithmic point of view. The slight differences you observe in performance are due to the randomness inherent in random forest.
