### ISSUE TITLE
arboreto package available in bioconda

### ISSUE THREAD

**Issue by vibbits** [aertslab/arboreto#4]
hi just a FYI - in the framework of setting the scene for more reproducible computational biology workflows, the arboreto  package is part of a pilot and has been added to [bioconda](https://anaconda.org/bioconda/arboreto). 
furthermore, we have targeted multiprocessing_on_dill at conda-forge to finally provide pySCENIC in bioconda. cheers

**Comment by tmoerman** [comment]
That's great, thanks!
